### ISSUE TITLE
need to change user name from ubunto to ec2-user

### ISSUE THREAD

**Issue by PLaRoche** [uriagassi/sash#11]
see http://stackoverflow.com/a/4342085

basically if using ubuntu@ you will get `Permission denied (publickey)`  need the user to be `ec2-user`

**Comment by uriagassi** [comment]
It depends on what kind of machine you have created. Canonical's releases use `ubuntu`.

If you work with some other user (like `ec2-user`), you can simply change it in the system environment `SASH_DEFAULT_USER` (as written in the README.md). You can even set usernames per machine using the `set_user` command.
